# Generated by Django 5.0.3 on 2024-03-08 21:36

import django.db.models.deletion
import django_countries.fields
import phone_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id_box', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('summ', models.DecimalField(decimal_places=2, max_digits=6)),
                ('choice', models.IntegerField()),
                ('type_distrybushin', models.CharField()),
                ('summ_now', models.CharField()),
                ('distrybushim_now', models.CharField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id_coin', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('numb_coin', models.IntegerField()),
                ('status', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id_news', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_by_tg', models.IntegerField(primary_key=True, serialize=False)),
                ('name_tg', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('email', models.EmailField(max_length=254)),
                ('language', models.CharField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('code_warification', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summ', models.DecimalField(decimal_places=2, max_digits=6)),
                ('nom_operation', models.IntegerField()),
                ('time', models.TimeField(auto_now=True)),
                ('status', models.CharField()),
                ('id_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.box')),
                ('id_by_tg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.user')),
            ],
        ),
        migrations.CreateModel(
            name='MassageUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('id_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.news')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.user')),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.coin')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.box')),
                ('id_by_tg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.user')),
            ],
        ),
    ]
