# Generated by Django 5.0.3 on 2024-03-09 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_by_tg', models.IntegerField(primary_key=True, serialize=False)),
                ('name_tg', models.CharField(max_length=255, verbose_name='Телеграм користувача')),
                ('name', models.CharField(max_length=255, verbose_name='Імя користувача')),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('language', models.CharField(default='ua')),
                ('country', models.CharField(default='Україна')),
                ('code_warification', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Клієнт',
                'verbose_name_plural': 'Клієнти',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id_news', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Текст Новин')),
            ],
            options={
                'verbose_name': 'Новини',
                'verbose_name_plural': 'Новини',
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id_box', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('summ', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tyme_open', models.IntegerField(default=0, verbose_name='Кількість відкриттів')),
                ('type_distrybushin', models.CharField(help_text='Рандомно|Рівномірно')),
                ('summ_now', models.DecimalField(decimal_places=2, max_digits=6)),
                ('distrybushim_now', models.CharField()),
                ('status', models.CharField(help_text='Активно|Неактивно')),
                ('user', models.ManyToManyField(related_name='user_box', to='box.client', verbose_name='Клієнт')),
            ],
            options={
                'verbose_name': 'Бокс',
                'verbose_name_plural': 'Бокси',
            },
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id_coin', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('numb_coin', models.IntegerField(verbose_name='Кількість монет')),
                ('status', models.CharField()),
                ('user', models.ManyToManyField(related_name='user_coin', to='box.client', verbose_name='Монети')),
            ],
            options={
                'verbose_name': 'Монета',
                'verbose_name_plural': 'Монети',
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.client')),
                ('id_coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.coin')),
            ],
        ),
        migrations.CreateModel(
            name='MassageUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.client')),
                ('id_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.news')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summ', models.DecimalField(decimal_places=2, max_digits=6)),
                ('nom_operation', models.IntegerField()),
                ('time', models.TimeField(auto_now=True)),
                ('status', models.CharField(help_text='Активна|Неактивна')),
                ('id_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.box')),
                ('id_by_tg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.client')),
            ],
            options={
                'verbose_name': 'Операції клієнта',
                'verbose_name_plural': 'Операції клієнтів',
            },
        ),
        migrations.CreateModel(
            name='UserBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.box')),
                ('id_by_tg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.client')),
            ],
        ),
    ]
