# Generated by Django 5.0.3 on 2024-03-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='summ_now',
            field=models.IntegerField(),
        ),
    ]
