# Generated by Django 5.0.3 on 2024-03-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0002_alter_box_summ_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='status',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='box',
            name='summ',
            field=models.IntegerField(),
        ),
    ]
