# Generated by Django 5.0.3 on 2024-03-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0003_alter_box_status_alter_box_summ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='id_box',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
