# Generated by Django 5.0.3 on 2024-03-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0004_alter_box_id_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='user',
            field=models.ManyToManyField(related_name='box_user', to='box.client', verbose_name='Клієнт'),
        ),
    ]
